#Database configurations
mysql:
  use: false #True if you want to use mysql
  host: "localhost" #The ip doesn't need port. Correct way: "127.0.0.1" | Wrong way: "127.0.0.1:0000"
  database: "epic" #Database name
  user: "root" #Username
  password: "123" #Password